name: .NET

on:
  push:
    branches: 
    - main
    paths:
    - src/**
    - .github/workflows/dotnet.yml
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - .github/workflows/dotnet.yml
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore -c:Release

    - name: Test Scalar
      run: dotnet test --no-build --verbosity normal -c:Release -e:DOTNET_EnableHWIntrinsic=0

    - name: Test Vector128
      run: dotnet test --no-build --verbosity normal -c:Release -e:DOTNET_EnableAVX2=0 -e:DOTNET_EnableAVX512F=0

    - name: Test Vector256
      run: dotnet test --no-build --verbosity normal -c:Release -e:DOTNET_EnableAVX512F=0
